# Generated by Django 6.0.5 on 2026-06-19 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campesino',
            fields=[
                ('id_campesino', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'campesino',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Contribuyente',
            fields=[
                ('id_contribuyente', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'contribuyente',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LecturaSensor',
            fields=[
                ('id_lectura', models.AutoField(primary_key=True, serialize=False)),
                ('valor_lectura', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_hora', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lectura_sensor',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=150, unique=True)),
                ('tipo_usuario', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'usuario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RecomendacionIa',
            fields=[
                ('id_recomendacion', models.AutoField(primary_key=True, serialize=False)),
                ('mensaje_ia', models.TextField(blank=True, null=True)),
                ('id_lectura', models.OneToOneField(blank=True, db_column='id_lectura', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_smart.lecturasensor')),
            ],
            options={
                'db_table': 'recomendacion_ia',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ResiduoOrganico',
            fields=[
                ('id_residuo', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_residuo', models.CharField(blank=True, max_length=100, null=True)),
                ('cantidad_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estado', models.CharField(blank=True, max_length=20, null=True)),
                ('id_contribuyente', models.ForeignKey(blank=True, db_column='id_contribuyente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_smart.contribuyente')),
            ],
            options={
                'db_table': 'residuo_organico',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id_sensor', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_sensor', models.CharField(blank=True, max_length=50, null=True)),
                ('id_campesino', models.ForeignKey(blank=True, db_column='id_campesino', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_smart.campesino')),
            ],
            options={
                'db_table': 'sensor',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='lecturasensor',
            name='id_sensor',
            field=models.ForeignKey(blank=True, db_column='id_sensor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_smart.sensor'),
        ),
        migrations.CreateModel(
            name='GestionLogistica',
            fields=[
                ('id_gestion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_asignacion', models.DateTimeField(blank=True, null=True)),
                ('id_campesino', models.ForeignKey(blank=True, db_column='id_campesino', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_smart.campesino')),
                ('id_residuo', models.OneToOneField(blank=True, db_column='id_residuo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_smart.residuoorganico')),
                ('id_usuario_alcaldia', models.ForeignKey(blank=True, db_column='id_usuario_alcaldia', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_smart.usuario')),
            ],
            options={
                'db_table': 'gestion_logistica',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='contribuyente',
            name='id_usuario',
            field=models.OneToOneField(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_smart.usuario'),
        ),
        migrations.AddField(
            model_name='campesino',
            name='id_usuario',
            field=models.OneToOneField(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_smart.usuario'),
        ),
    ]
