# Generated by Django 6.0.5 on 2026-06-25 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_smart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='comprobante_registro',
            field=models.FileField(blank=True, null=True, upload_to='comprobantes/'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='estado_cuenta',
            field=models.CharField(blank=True, default='activo', max_length=30),
        ),
    ]
