# Generated by Django 6.0.6 on 2026-06-26 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_smart', '0002_usuario_comprobante_registro_usuario_estado_cuenta'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudResiduo',
            fields=[
                ('id_solicitud_residuo', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(blank=True, default='pendiente', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('id_campesino', models.ForeignKey(blank=True, db_column='id_campesino', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_smart.campesino')),
                ('id_residuo', models.ForeignKey(blank=True, db_column='id_residuo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_smart.residuoorganico')),
            ],
            options={
                'db_table': 'solicitud_residuo',
                'managed': True,
            },
        ),
    ]
