# Generated by Django 6.0.5 on 2026-06-26 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_smart', '0003_solicitudresiduo'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudresiduo',
            name='cantidad_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='solicitudresiduo',
            name='tipo_residuo',
            field=models.CharField(blank=True, choices=[('SECO', 'Residuo Seco (Cartón, Papel, Hojas secas, Aserrín)'), ('HUMEDO', 'Residuo Húmedo (Restos de frutas, verduras, café, orgánicos)')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='solicitudresiduo',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='residuoorganico',
            name='tipo_residuo',
            field=models.CharField(blank=True, choices=[('SECO', 'Residuo Seco (Cartón, Papel, Hojas secas, Aserrín)'), ('HUMEDO', 'Residuo Húmedo (Restos de frutas, verduras, café, orgánicos)')], max_length=20, null=True),
        ),
    ]
