# Generated by Django 6.0.6 on 2026-06-26 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_smart', '0004_solicitudresiduo_cantidad_kg_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventarioAlcaldia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_residuo', models.CharField(choices=[('SECO', 'Seco'), ('HUMEDO', 'Húmedo')], max_length=10, unique=True)),
                ('cantidad_total_kg', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'db_table': 'inventario_alcaldia',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='gestionlogistica',
            name='cantidad_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='gestionlogistica',
            name='tipo_residuo',
            field=models.CharField(blank=True, choices=[('SECO', 'Seco'), ('HUMEDO', 'Húmedo')], max_length=10, null=True),
        ),
    ]
