# Generated by Django 6.0.5 on 2026-06-26 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_smart', '0005_inventarioalcaldia_gestionlogistica_cantidad_kg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestionlogistica',
            name='ubicacion_entrega',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
