# Generated by Codex on 2026-06-30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_smart', '0007_auditoria_residuo_diagnostico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alcaldia',
            fields=[
                ('id_alcaldia', models.AutoField(primary_key=True, serialize=False)),
                ('id_usuario', models.OneToOneField(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_smart.usuario')),
            ],
            options={
                'db_table': 'alcaldia',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SolicitudSensor',
            fields=[
                ('id_solicitud_sensor', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_sensor', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACEPTADO', 'Aceptado'), ('RECHAZADO', 'Rechazado'), ('activo', 'Activo'), ('pendiente_activacion', 'Pendiente de activacion'), ('pendiente_aprobacion', 'Pendiente de aprobacion'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='PENDIENTE', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('id_campesino', models.ForeignKey(blank=True, db_column='id_campesino', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_smart.campesino')),
            ],
            options={
                'db_table': 'solicitud_sensor',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='usuario',
            name='estado_cuenta',
            field=models.CharField(blank=True, choices=[('PENDIENTE', 'Pendiente'), ('ACEPTADO', 'Aceptado'), ('RECHAZADO', 'Rechazado'), ('activo', 'Activo'), ('pendiente_activacion', 'Pendiente de activacion'), ('pendiente_aprobacion', 'Pendiente de aprobacion'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='activo', max_length=30),
        ),
    ]
