# Generated by Codex on 2026-06-30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_smart', '0008_alcaldia_solicitudsensor_estado_admin'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE usuario DROP CONSTRAINT IF EXISTS usuario_tipo_usuario_check;
                ALTER TABLE usuario
                ADD CONSTRAINT usuario_tipo_usuario_check
                CHECK (
                    tipo_usuario IS NULL
                    OR tipo_usuario IN (
                        'Campesino',
                        'Contribuyente',
                        'Alcaldia',
                        'Alcaldía',
                        'admin'
                    )
                );
            """,
            reverse_sql="""
                ALTER TABLE usuario DROP CONSTRAINT IF EXISTS usuario_tipo_usuario_check;
                ALTER TABLE usuario
                ADD CONSTRAINT usuario_tipo_usuario_check
                CHECK (
                    tipo_usuario IS NULL
                    OR tipo_usuario IN (
                        'Campesino',
                        'Contribuyente',
                        'Alcaldia',
                        'Alcaldía'
                    )
                );
            """,
        ),
    ]
