# Generated by Django 6.0.6 on 2026-06-30 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_smart', '0011_solicitudsensor_fecha_entrega_motivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='residuoorganico',
            name='contraoferta_alcaldia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='residuoorganico',
            name='peso_estimado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='residuoorganico',
            name='precio_sugerido_contribuyente',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='solicitudresiduo',
            name='cantidad_solicitada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='solicitudresiduo',
            name='contraoferta_alcaldia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='solicitudresiduo',
            name='precio_ofrecido_campesino',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='residuoorganico',
            name='estado',
            field=models.CharField(blank=True, choices=[('Pendiente', 'Pendiente'), ('Aceptado', 'Aceptado'), ('Rechazado', 'Rechazado'), ('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('CONTRAOFERTA_ALCALDIA', 'Contraoferta de alcaldia'), ('ACEPTADO_POR_CONTRIBUYENTE', 'Aceptado por contribuyente'), ('ACEPTADO_POR_CAMPESINO', 'Aceptado por campesino')], default='PENDIENTE', max_length=30),
        ),
        migrations.AlterField(
            model_name='solicitudresiduo',
            name='estado',
            field=models.CharField(blank=True, default='PENDIENTE', max_length=30),
        ),
    ]
