# Generated by Django 6.0.5 on 2026-07-23 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_smart', '0012_residuoorganico_contraoferta_alcaldia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudresiduo',
            name='estado',
            field=models.CharField(blank=True, choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('CONTRAOFERTA_ALCALDIA', 'Contraoferta de alcaldia'), ('ACEPTADO_POR_CAMPESINO', 'Aceptado por campesino')], default='PENDIENTE', max_length=30),
        ),
    ]
