# Generated by Django 6.0.5 on 2026-08-09 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_smart', '0015_dispositivos_iot_y_telemetria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='estado_cuenta',
            field=models.CharField(blank=True, choices=[('PENDIENTE', 'Pendiente'), ('ACEPTADO', 'Aceptado'), ('RECHAZADO', 'Rechazado'), ('activo', 'Activo'), ('pendiente_activacion', 'Pendiente de activacion'), ('pendiente_aprobacion', 'Pendiente de aprobacion'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('EN_CAMINO', 'En camino'), ('ENTREGADO', 'Entregado')], default='activo', max_length=30),
        ),
    ]
