# Generated by Django 6.0.5 on 2026-09-04 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_smart', '0017_inventarioalcaldia_presencia_citricos'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestionlogistica',
            name='presencia_citricos',
            field=models.CharField(default='Ninguna', max_length=20),
        ),
        migrations.AddField(
            model_name='solicitudresiduo',
            name='presencia_citricos',
            field=models.CharField(default='Ninguna', max_length=20),
        ),
    ]
