# Generated by Django 6.0.5 on 2026-09-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_smart', '0018_agregar_citricos_solicitudes_asignaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recomendacionia',
            name='id_lectura',
            field=models.ForeignKey(
                blank=True,
                db_column='id_lectura',
                null=True,
                on_delete=models.DO_NOTHING,
                related_name='recomendaciones_ia',
                to='app_smart.lecturasensor',
            ),
        ),
        migrations.AddField(
            model_name='recomendacionia',
            name='archivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='recomendaciones_ia/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='recomendacionia',
            name='campesino',
            field=models.ForeignKey(
                db_column='id_campesino',
                null=True,
                on_delete=models.DO_NOTHING,
                related_name='recomendaciones_ia',
                to='app_smart.usuario',
            ),
        ),
        migrations.AddField(
            model_name='recomendacionia',
            name='datos_entrada',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='recomendacionia',
            name='fecha_generacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='recomendacionia',
            name='titulo',
            field=models.CharField(default='Diagnóstico agronómico', max_length=160),
            preserve_default=False,
        ),
        migrations.AlterModelOptions(
            name='recomendacionia',
            options={'managed': True, 'ordering': ['-fecha_generacion']},
        ),
    ]
