# Generated by Django 6.0.5 on 2026-09-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_smart', '0021_sensor_thingspeak_channel_unico'),
    ]

    operations = [
        migrations.AddField(
            model_name='recomendacionia',
            name='contenido_pdf',
            field=models.BinaryField(blank=True, editable=False, null=True),
        ),
    ]
