# Generated by Django 6.0.5 on 2026-09-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_smart', '0022_recomendacionia_contenido_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='comprobante_contenido',
            field=models.BinaryField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='comprobante_nombre',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
